services:
  database:
    container_name: YGOODB
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    # volumes:
    #   - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}